# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.pit_transform <- function(u, shape, distribution) {
    .Call(`_tsmarch_pit_transform`, u, shape, distribution)
}

.copula_constant_normal <- function(u, method) {
    .Call(`_tsmarch_copula_constant_normal`, u, method)
}

.copula_constant_student <- function(shape, u) {
    .Call(`_tsmarch_copula_constant_student`, shape, u)
}

.copula_dynamic_normal <- function(alpha, gamma, beta, u, dccorder) {
    .Call(`_tsmarch_copula_dynamic_normal`, alpha, gamma, beta, u, dccorder)
}

.copula_dynamic_student <- function(alpha, gamma, beta, shape, u, dccorder) {
    .Call(`_tsmarch_copula_dynamic_student`, alpha, gamma, beta, shape, u, dccorder)
}

.copula_constant_normal_filter <- function(u, method, n_update) {
    .Call(`_tsmarch_copula_constant_normal_filter`, u, method, n_update)
}

.copula_constant_student_filter <- function(shape, u, n_update) {
    .Call(`_tsmarch_copula_constant_student_filter`, shape, u, n_update)
}

.copula_dynamic_normal_filter <- function(alpha, gamma, beta, u, dccorder, n_update) {
    .Call(`_tsmarch_copula_dynamic_normal_filter`, alpha, gamma, beta, u, dccorder, n_update)
}

.copula_dynamic_student_filter <- function(alpha, gamma, beta, shape, u, dccorder, n_update) {
    .Call(`_tsmarch_copula_dynamic_student_filter`, alpha, gamma, beta, shape, u, dccorder, n_update)
}

.copula_dynamic_simulate <- function(alpha, gamma, beta, shape, Qbar, Nbar, Qinit, Zinit, std_noise, timesteps, burn, dccorder, distribution) {
    .Call(`_tsmarch_copula_dynamic_simulate`, alpha, gamma, beta, shape, Qbar, Nbar, Qinit, Zinit, std_noise, timesteps, burn, dccorder, distribution)
}

.copula_constant_simulate <- function(shape, R, std_noise, timesteps, distribution) {
    .Call(`_tsmarch_copula_constant_simulate`, shape, R, std_noise, timesteps, distribution)
}

.copula_adcc_constraint <- function(alpha, gamma, beta, shape, u, dccorder, distribution) {
    .Call(`_tsmarch_copula_adcc_constraint`, alpha, gamma, beta, shape, u, dccorder, distribution)
}

.matrix_sign <- function(x) {
    .Call(`_tsmarch_matrix_sign`, x)
}

.make_correlation <- function(data, method) {
    .Call(`_tsmarch_make_correlation`, data, method)
}

.make_psd <- function(x, eig_tol, conv_tol, posd_tol, maxit) {
    .Call(`_tsmarch_make_psd`, x, eig_tol, conv_tol, posd_tol, maxit)
}

.p2P <- function(values, m) {
    .Call(`_tsmarch_p2P`, values, m)
}

.is_psd <- function(x) {
    .Call(`_tsmarch_is_psd`, x)
}

.array_mean <- function(x) {
    .Call(`_tsmarch_array_mean`, x)
}

.dcc_constant_normal <- function(Z, S) {
    .Call(`_tsmarch_dcc_constant_normal`, Z, S)
}

.dcc_constant_student <- function(Z, S, shape) {
    .Call(`_tsmarch_dcc_constant_student`, Z, S, shape)
}

.dcc_dynamic_normal <- function(alpha, gamma, beta, z, s, dccorder) {
    .Call(`_tsmarch_dcc_dynamic_normal`, alpha, gamma, beta, z, s, dccorder)
}

.dcc_dynamic_student <- function(alpha, gamma, beta, shape, z, s, dccorder) {
    .Call(`_tsmarch_dcc_dynamic_student`, alpha, gamma, beta, shape, z, s, dccorder)
}

.adcc_constraint <- function(alpha, gamma, beta, shape, z, dccorder) {
    .Call(`_tsmarch_adcc_constraint`, alpha, gamma, beta, shape, z, dccorder)
}

.dcc_constant_normal_filter <- function(Z, S, n_update) {
    .Call(`_tsmarch_dcc_constant_normal_filter`, Z, S, n_update)
}

.dcc_constant_student_filter <- function(shape, Z, S, n_update) {
    .Call(`_tsmarch_dcc_constant_student_filter`, shape, Z, S, n_update)
}

.dcc_dynamic_normal_filter <- function(alpha, gamma, beta, z, s, dccorder, n_update) {
    .Call(`_tsmarch_dcc_dynamic_normal_filter`, alpha, gamma, beta, z, s, dccorder, n_update)
}

.dcc_dynamic_student_filter <- function(alpha, gamma, beta, shape, z, s, dccorder, n_update) {
    .Call(`_tsmarch_dcc_dynamic_student_filter`, alpha, gamma, beta, shape, z, s, dccorder, n_update)
}

.dcc_dynamic_simulate <- function(alpha, gamma, beta, shape, Qbar, Nbar, Qinit, Zinit, std_noise, timesteps, burn, dccorder, distribution) {
    .Call(`_tsmarch_dcc_dynamic_simulate`, alpha, gamma, beta, shape, Qbar, Nbar, Qinit, Zinit, std_noise, timesteps, burn, dccorder, distribution)
}

.dcc_constant_simulate <- function(shape, R, std_noise, timesteps, distribution) {
    .Call(`_tsmarch_dcc_constant_simulate`, shape, R, std_noise, timesteps, distribution)
}

.rmvnorm <- function(R, Z) {
    .Call(`_tsmarch_rmvnorm`, R, Z)
}

.rmvt <- function(R, Z, nu) {
    .Call(`_tsmarch_rmvt`, R, Z, nu)
}

.interpolate_window <- function(x, y, z, w = -1L) {
    .Call(`_tsmarch_interpolate_window`, x, y, z, w)
}

.nigmvcf <- function(z, alpha, beta, delta, mu) {
    .Call(`_tsmarch_nigmvcf`, z, alpha, beta, delta, mu)
}

.cfinvnig <- function(z, step, alpha, beta, delta, mu) {
    .Call(`_tsmarch_cfinvnig`, z, step, alpha, beta, delta, mu)
}

.ghypfn <- function(lambda, alpha, beta, delta, z) {
    .Call(`_tsmarch_ghypfn`, lambda, alpha, beta, delta, z)
}

.ghypmvcf <- function(z, lambda, alpha, beta, delta, mu) {
    .Call(`_tsmarch_ghypmvcf`, z, lambda, alpha, beta, delta, mu)
}

.cfinvghyp <- function(z, step, lambda, alpha, beta, delta, mu) {
    .Call(`_tsmarch_cfinvghyp`, z, step, lambda, alpha, beta, delta, mu)
}

.gogarch_covariance <- function(V, A) {
    .Call(`_tsmarch_gogarch_covariance`, V, A)
}

.gogarch_correlation <- function(V, A) {
    .Call(`_tsmarch_gogarch_correlation`, V, A)
}

.coskewness_sigma <- function(sigmas) {
    .Call(`_tsmarch_coskewness_sigma`, sigmas)
}

.coskewness_block <- function(skew) {
    .Call(`_tsmarch_coskewness_block`, skew)
}

.gogarch_coskewness <- function(A, S, V, standardize) {
    .Call(`_tsmarch_gogarch_coskewness`, A, S, V, standardize)
}

.combn <- function(n, m) {
    .Call(`_tsmarch_combn`, n, m)
}

.cokurt_pairs <- function(n) {
    .Call(`_tsmarch_cokurtosis_pairs`, n)
}

.cokurt_index <- function(s, values) {
    .Call(`_tsmarch_cokurtosis_block`, s, values)
}

.cokurtosis_sigma <- function(sigmas) {
    .Call(`_tsmarch_cokurtosis_sigma`, sigmas)
}

.gogarch_cokurtosis <- function(A, K, V, standardize) {
    .Call(`_tsmarch_gogarch_cokurtosis`, A, K, V, standardize)
}

.gogarch_skewness_weighted <- function(A, S, w) {
    .Call(`_tsmarch_gogarch_skewness_weighted`, A, S, w)
}

.gogarch_kurtosis_weighted <- function(A, K, V, w) {
    .Call(`_tsmarch_gogarch_cokurtosis_weighted`, A, K, V, w)
}

.gogarch_covariance_weighted <- function(V, A, w) {
    .Call(`_tsmarch_gogarch_covariance_weighted`, V, A, w)
}

.gogarch_kurtosis_weighted_sim <- function(A, sig, ku, weights, nsim, n) {
    .Call(`_tsmarch_gogarch_cokurtosis_weighted_sim`, A, sig, ku, weights, nsim, n)
}

.aggregate_mu <- function(mu, w) {
    .Call(`_tsmarch_aggregate_mu`, mu, w)
}

.aggregate_sigma <- function(sigma, w) {
    .Call(`_tsmarch_aggregate_sigma`, sigma, w)
}

.tril2sym <- function(values, m, diag) {
    .Call(`_tsmarch_tril2sym`, values, m, diag)
}

.sym2tril <- function(S, diag) {
    .Call(`_tsmarch_sym2tril`, S, diag)
}

.generate_constant_covariance <- function(correlation, sigmas, residuals) {
    .Call(`_tsmarch_generate_constant_covariance`, correlation, sigmas, residuals)
}

.generate_dynamic_covariance <- function(correlation, sigmas, residuals) {
    .Call(`_tsmarch_generate_dynamic_covariance`, correlation, sigmas, residuals)
}

.cor2cov <- function(r, sigma, m) {
    .Call(`_tsmarch_cor2cov`, r, sigma, m)
}

.cor2cov2 <- function(r, sigma, m) {
    .Call(`_tsmarch_cor2cov2`, r, sigma, m)
}

.qnig <- function(p, mu, delta, alpha, beta) {
    .Call(`_tsmarch_qnig`, p, mu, delta, alpha, beta)
}

.radical_recursion <- function(k, sigma, samples, replications, whitening_signal, whitening_matrix, dewhitening_matrix, mixed_signal, mixed_mean, trace) {
    .Call(`_tsmarch_radical_recursion`, k, sigma, samples, replications, whitening_signal, whitening_matrix, dewhitening_matrix, mixed_signal, mixed_mean, trace)
}

